#!/usr/bin/env python3
# pylint: disable=import-outside-toplevel,broad-exception-caught,protected-access
"""Inspect and dump samples from antllm .scatter/.lazy datasets.

Similar to antllm's data/tools/check_outputs.py but works standalone
with direct directory paths — no YAML config or training framework needed.

Usage examples:

  # Dump first 5 samples from a single scatter directory (sliding_window)
  python check_lazy_outputs.py --scatter-dir /path/to/dataset.scatter --num-samples 5

  # Dump with specific seq_length and eos_token_id
  python check_lazy_outputs.py --scatter-dir /path/to/dataset.scatter \
      --seq-length 4096 --eos-token-id 2 --num-samples 10

  # Dump from multiple datasets with blending weights
  python check_lazy_outputs.py \
      --scatter-dir /path/to/ds1.scatter /path/to/ds2.scatter \
      --weights 0.7 0.3 --num-samples 20

  # Use map mode with index_mapping
  python check_lazy_outputs.py --scatter-dir /path/to/dataset.scatter \
      --mode map --index-mapping-path /path/to/index_mapping_dir

  # Decode tokens with a tokenizer
  python check_lazy_outputs.py --scatter-dir /path/to/dataset.scatter \
      --tokenizer-path /path/to/tokenizer --num-samples 3

  # Save output to numpy files
  python check_lazy_outputs.py --scatter-dir /path/to/dataset.scatter \
      --num-samples 100 --output-dir /tmp/check_outputs

  # Dump ALL scatter groups (for comparison with antllm check_outputs.py)
  # Each group outputs to <output-dir>/<group_id>/step_*.npy
  python check_lazy_outputs.py --scatter-dir /path/to/dataset.scatter \
      --loader-scatter -4 --batch-per-step 8 --num-steps 10 \
      --dump-groups --output-dir /tmp/maxtext_groups

  # Load all parameters from a JSON config file (generated by antllm check_outputs.py)
  python check_lazy_outputs.py --config /tmp/antllm_dump/maxtext_params.json \
      --dump-groups --num-steps 10 --output-dir /tmp/maxtext_dump
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
import time

import numpy as np

# Allow running from the repo root or tools/lazy_dataloader/ directory
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(_REPO_ROOT, "src"))

from maxtext.input_pipeline._lazy_datasource import (
    LazyIndexedDataset,
    MultiShardLazyDataSource,
)
from maxtext.input_pipeline._lazy_blending import LazyBlendedDataSource


# JSON key -> argparse dest (only for non-obvious mappings)
_CONFIG_KEY_MAP = {
    "scatter_dirs": "scatter_dir",
    "loader_mode": "mode",
}

# argparse defaults that should NOT be treated as "user explicitly set"
# when deciding whether CLI overrides config. We track which args the user
# actually provided on the command line via _CLI_SENTINEL.
_CLI_SENTINEL = object()


def _load_config(config_path):
  """Load JSON config file and return as dict."""
  with open(config_path, encoding="utf-8") as f:
    return json.load(f)


def _apply_config(args, config, parser):
  """Apply config dict values to args, with CLI args taking precedence.

  For each key in config, map it to the argparse dest name, and set it on
  args only if the user did not explicitly provide that arg on the CLI.
  """
  # Build set of args the user explicitly provided on CLI
  # by comparing against the sentinel defaults we injected
  cli_provided = set()
  for action in parser._actions:
    if action.dest == "help":
      continue
    val = getattr(args, action.dest, _CLI_SENTINEL)
    if val is not _CLI_SENTINEL and val != action.default:
      cli_provided.add(action.dest)
  # Special: scatter_dir is None by default, so if user passed it, it's non-None
  if args.scatter_dir is not None:
    cli_provided.add("scatter_dir")

  for key, value in config.items():
    if value is None:
      continue
    dest = _CONFIG_KEY_MAP.get(key, key)
    # micro_batch_size -> batch_per_step (fallback)
    if key == "micro_batch_size" and "batch_per_step" not in config:
      dest = "batch_per_step"
    elif key == "micro_batch_size":
      continue  # batch_per_step in config takes precedence
    # drop_last (bool) -> no_drop_last (inverted)
    if key == "drop_last":
      dest = "no_drop_last"
      value = not value
    # Skip keys we don't recognize
    if not hasattr(args, dest):
      continue
    # CLI takes precedence
    if dest in cli_provided:
      continue
    setattr(args, dest, value)


def get_args():
  """Parse command-line arguments."""
  parser = argparse.ArgumentParser(
      description="Inspect and dump samples from .scatter/.lazy datasets",
      formatter_class=argparse.RawDescriptionHelpFormatter,
  )
  parser.add_argument(
      "--config",
      type=str,
      default=None,
      help="JSON config file (e.g. maxtext_params.json from antllm check_outputs.py). "
      "All parameters can be specified in the JSON. CLI args override config values.",
  )
  parser.add_argument(
      "--scatter-dir",
      type=str,
      nargs="+",
      default=None,
      help="Path(s) to .scatter directories. Multiple paths enable blending.",
  )
  parser.add_argument(
      "--data-root",
      type=str,
      default=None,
      help="Prefix path prepended to each scatter-dir. Useful when scatter_dirs in "
      "maxtext_params.json are relative paths.",
  )
  parser.add_argument(
      "--weights",
      type=float,
      nargs="+",
      default=None,
      help="Blending weights (one per scatter-dir). Required when multiple scatter-dirs are given.",
  )
  parser.add_argument("--seq-length", type=int, default=4096, help="Sequence length (default: 4096)")
  parser.add_argument("--eos-token-id", type=int, default=2, help="EOS token ID (default: 2)")
  parser.add_argument("--cls-token-id", type=int, default=-1, help="CLS token ID (-1 = disabled)")
  parser.add_argument("--add-cls", action="store_true", help="Prepend CLS at document segments")
  parser.add_argument("--data-type", type=str, default="text", help="Field name in .lazy dir (default: text)")
  parser.add_argument(
      "--mode",
      type=str,
      default="sliding_window",
      choices=["sliding_window", "map", "pack"],
      help="Loader mode (default: sliding_window)",
  )
  parser.add_argument("--index-mapping-path", type=str, default=None, help="Path for map mode index_mapping.npy dir")
  parser.add_argument("--bin-index-path", type=str, default=None, help="Path for pack mode bin index dir")
  parser.add_argument(
      "--bfd-pack",
      type=str,
      default=None,
      help="Per-dataset BFD pack control. 'ALL' = all datasets use pack mode. "
      "Comma-separated dataset names (e.g. 'ds1,ds2') = only those datasets use pack, "
      "rest use sliding_window. Overrides --mode for matched datasets.",
  )
  parser.add_argument(
      "--bfd-pack-sort-by-lens",
      action="store_true",
      help="Sort samples by length mod seq_length (descending) before BFD packing. (antllm bfd_pack_sort_by_lens)",
  )
  parser.add_argument("--num-samples", type=int, default=5, help="Number of samples to dump (default: 5)")
  parser.add_argument("--start-index", type=int, default=0, help="Starting sample index (default: 0)")
  parser.add_argument("--output-dir", type=str, default=None, help="Save samples as .npy files to this directory")
  parser.add_argument("--tokenizer-path", type=str, default=None, help="Path to HF tokenizer for decoding")
  parser.add_argument("--no-decode", action="store_true", help="Skip token decoding even if tokenizer is available")
  parser.add_argument("--show-stats", action="store_true", help="Show dataset statistics")
  parser.add_argument(
      "--drop-last", action="store_true", default=True, help="Drop last incomplete sample (default: True)"
  )
  parser.add_argument("--no-drop-last", action="store_true", help="Keep last incomplete sample")
  parser.add_argument(
      "--shuffle-seed",
      type=int,
      default=-1,
      help="Shuffle blending indices with this seed (antllm dataset_index_shuffle_seed). -1 = no shuffle.",
  )
  parser.add_argument(
      "--shuffle-only-dataset",
      action="store_true",
      help=(
          "Only shuffle dataset_index, regenerate dataset_sample_index"
          " per dataset (antllm dataset_index_shuffle_only_dataset)."
      ),
  )
  parser.add_argument(
      "--split",
      type=str,
      default=None,
      help="Train/valid/test split ratio, e.g. '999,1,0'.",
  )
  parser.add_argument(
      "--split-parts",
      type=str,
      default="train",
      help="Which split parts to output: 'train', 'valid', 'test', or comma-separated "
      "like 'train,valid'. Each part gets its own subdirectory under --output-dir. "
      "(default: train)",
  )
  parser.add_argument(
      "--weight-mode",
      type=str,
      default="epoch",
      choices=["epoch", "ratio"],
      help="How to compute total blend size. epoch: size=sum(w*len(ds)). ratio: size=sum(len(ds)).",
  )
  parser.add_argument(
      "--trace",
      action="store_true",
      help="Print routing details (global_idx -> local_idx -> shard -> inner_idx) for each sample.",
  )
  parser.add_argument(
      "--raw",
      action="store_true",
      help="Read directly from MultiShardLazyDataSource (skip blending/shuffle/split).",
  )
  parser.add_argument(
      "--debug-binary",
      action="store_true",
      help="Print raw binary diagnostics: first tokens from each shard's binary file, "
      "document lengths, and sliding-window assembly details for sample 0.",
  )
  parser.add_argument(
      "--loader-online-shuffle",
      action="store_true",
      help="Enable per-dataset online shuffle (antllm loader_online_shuffle). "
      "Shuffles sample indices within each AllSampleLazyLoader per epoch.",
  )
  parser.add_argument(
      "--loader-seed",
      type=int,
      default=1234,
      help="Seed for loader online shuffle (default: 1234, matching antllm default).",
  )
  parser.add_argument(
      "--loader-scatter",
      type=int,
      default=-1,
      help="Scatter shard grouping. -1=all shards (default). "
      "Positive N: read 1 shard (id=process-index%%N). "
      "Negative -N: merge mode, read total_shards/N shards.",
  )
  parser.add_argument(
      "--process-index",
      type=int,
      default=0,
      help="Simulated host/process index for scatter shard assignment (default: 0).",
  )
  parser.add_argument(
      "--dump-groups",
      action="store_true",
      help="Dump samples from ALL scatter groups (like antllm check_outputs.py). "
      "Iterates group_id in range(abs(loader_scatter)), each group consumes "
      "batch_per_step samples sequentially per step. "
      "Output: <output-dir>/<group_id>/step_*.npy. Requires --output-dir.",
  )
  parser.add_argument(
      "--batch-per-step",
      type=int,
      default=None,
      help="Samples per step per scatter group in --dump-groups mode. "
      "Equivalent to antllm's global_batch_size / abs(loader_scatter). "
      "Defaults to --num-samples if not set.",
  )
  parser.add_argument(
      "--num-steps",
      type=int,
      default=5,
      help="Number of steps to simulate in --simulate-global mode (default: 5).",
  )
  parser.add_argument(
      "--blend-cache-dir",
      type=str,
      default=None,
      help="Cache directory for blending indices. When set, dataset_index/dataset_sample_index "
      "arrays are saved after first computation and mmap-loaded on subsequent runs.",
  )
  parser.add_argument(
      "--digest",
      action="store_true",
      help="Dump SHA256 + shape + token_sum per step as .jsonl instead of full .npy. "
      "Minimal storage for large-scale comparison with antllm --slim digest output.",
  )
  parser.add_argument(
      "--debug-blend",
      action="store_true",
      help="Print blend-epoch diagnostics: blend _size, sub-source total_samples, "
      "loader_online_shuffle, and whether blend_epoch > 0 at the accessed indices. "
      "Useful for verifying whether the cross-blend-epoch patch has any effect.",
  )
  parser.add_argument(
      "--consumed-steps",
      type=int,
      default=0,
      help="Skip this many steps before dumping (for testing cross-epoch scenarios). "
      "Converted to consumed_samples = consumed_steps * batch_per_step internally.",
  )
  parser.add_argument(
      "--random-steps",
      type=int,
      default=None,
      help="Randomly sample N step indices from --step-range instead of dumping sequential steps. "
      "Useful for spot-checking large training runs without dumping every step.",
  )
  parser.add_argument(
      "--step-range",
      type=int,
      nargs=2,
      metavar=("START", "END"),
      default=None,
      help="Step range [START, END) for --random-steps sampling (default: [0, num_steps)).",
  )
  parser.add_argument(
      "--seed",
      type=int,
      default=42,
      help="Random seed for --random-steps (default: 42). Use the same seed on both sides to compare.",
  )
  args = parser.parse_args()

  # Apply config file if provided (CLI args override config values)
  if args.config:
    config = _load_config(args.config)
    _apply_config(args, config, parser)
    print(f"  Loaded config from {args.config}")

  # Validate: scatter_dir must come from CLI or config
  if not args.scatter_dir:
    parser.error("--scatter-dir is required (either via CLI or --config)")

  # Prepend data-root to scatter dirs if specified
  if args.data_root:
    args.scatter_dir = [os.path.join(args.data_root, d) for d in args.scatter_dir]

  return args


def _resolve_mode_for_tool(args, scatter_dir: str) -> str:
  """Resolve loader mode for a scatter_dir, supporting per-dataset pack via --bfd-pack."""
  bfd_pack = getattr(args, "bfd_pack", None)
  if not bfd_pack:
    return args.mode
  ds_name = os.path.basename(scatter_dir).replace(".scatter", "")
  if bfd_pack == "ALL" or ds_name in {n.strip() for n in bfd_pack.split(",")}:
    return "pack"
  return "sliding_window"


def build_source(args):
  """Build data source(s) from command-line arguments.

  Replicates the antllm pipeline order:
    1. Build per-scatter MultiShardLazyDataSource
    2. Wrap in LazyBlendedDataSource (even single dataset, if shuffle-seed given)
    3. Apply split (train/valid/test)
  """
  # antllm convention: internal seq_length = user_seq_length + 1
  effective_seq = args.seq_length + 1
  cls_token_id = args.cls_token_id if args.cls_token_id >= 0 else None
  drop_last = not args.no_drop_last

  sources = []
  for scatter_dir in args.scatter_dir:
    mode = _resolve_mode_for_tool(args, scatter_dir)
    source = MultiShardLazyDataSource(
        scatter_dir=scatter_dir,
        mode=mode,
        seq_length=effective_seq,
        eos_token_id=args.eos_token_id,
        data_type=args.data_type,
        cls_token_id=cls_token_id,
        add_cls=args.add_cls,
        drop_last=drop_last,
        loader_online_shuffle=args.loader_online_shuffle,
        loader_seed=args.loader_seed,
        index_mapping_path=args.index_mapping_path,
        bin_index_base_path=args.bin_index_path,
        bfd_pack_sort_by_lens=args.bfd_pack_sort_by_lens,
        loader_scatter=args.loader_scatter,
        process_index=args.process_index,
    )
    per_shard = [len(l) for l in source._loaders]
    print(f"  [{scatter_dir}] shards={len(source._loaders)}, samples={len(source)}")
    print(f"  per_shard_samples: {per_shard}")
    print(f"  cnt_ends: {source._cnt_ends.tolist()}")
    sources.append(source)

  # Blending (or single-dataset with shuffle)
  if len(sources) > 1 or args.shuffle_seed > 0:
    raw_weights = args.weights
    if raw_weights is None:
      raw_weights = [1.0] * len(sources)
    if len(raw_weights) != len(sources):
      raise ValueError(f"Number of weights ({len(raw_weights)}) must match scatter-dirs ({len(sources)})")

    # Compute total_size and normalize weights (matching antllm configure_data.py)
    if args.weight_mode == "epoch":
      # antllm epoch mode: size = int(sum(w * len(ds))), normalize by int(sum)
      # matching antllm configure_data.py:265
      weighted = [w * len(s) for w, s in zip(raw_weights, sources)]
      total = sum(weighted)
      total_size = int(total)
      weights = np.array([w / total_size for w in weighted], dtype=np.float64)
    else:
      weights = np.array(raw_weights, dtype=np.float64)
      weights = weights / weights.sum()
      total_size = sum(len(s) for s in sources)

    print(f"  Blending: weight_mode={args.weight_mode}, raw_weights={raw_weights}")
    print(
        f"  Blending: norm_weights={weights.tolist()}, total_size={total_size},"
        f" shuffle_seed={args.shuffle_seed}, shuffle_only_dataset={args.shuffle_only_dataset}"
    )
    result = LazyBlendedDataSource(
        sources,
        weights,
        total_size,
        shuffle_seed=args.shuffle_seed,
        shuffle_only_dataset=args.shuffle_only_dataset,
        cache_dir=args.blend_cache_dir,
        process_index=args.process_index,
        loader_scatter=args.loader_scatter,
    )
    # Print first few indices for cross-checking with antllm
    print(f"  dataset_index[:10]: {result.dataset_index[:10].tolist()}")
    print(f"  dataset_sample_index[:10]: {result.dataset_sample_index[:10].tolist()}")
  else:
    result = sources[0]

  # Split (antllm split: "999,1,0" -> train 99.9%, valid 0.1%, test 0%)
  if args.split:
    split_ratios = _parse_split(args.split)
    if split_ratios is not None:
      parts = _split_source(result, split_ratios)
      part_names = ["train", "valid", "test"]
      requested = {p.strip() for p in args.split_parts.split(",")}
      split_results = {}
      for i, name in enumerate(part_names):
        if parts[i] is not None:
          print(f"  Split {args.split} -> {name}={len(parts[i])} samples")
          if name in requested:
            split_results[name] = parts[i]
      if split_results:
        return split_results
      # Fallback: no requested parts found, return train
      if parts[0] is not None:
        return {"train": parts[0]}

  return {"train": result}


def _parse_split(split_str):
  """Parse split ratio string like '999,1,0' into normalized [train, valid, test]."""
  parts = split_str.replace("/", ",").split(",")
  splits = [float(s) for s in parts]
  while len(splits) < 3:
    splits.append(0.0)
  splits = splits[:3]
  total = sum(splits)
  return [s / total for s in splits]


def _split_source(source, split_ratios):
  """Split a source into train/valid/test by ratio."""
  total = len(source)
  start_idx = 0
  residual_idx = 0.0
  results = [None, None, None]
  for i, ratio in enumerate(split_ratios):
    if ratio != 0:
      proportion = total * ratio
      residual_idx += proportion % 1
      split_size = int(int(proportion) + residual_idx)
      results[i] = _SliceSource(source, start_idx, start_idx + max(split_size, 1))
      start_idx += split_size
      residual_idx %= 1
  return results


class _SliceSource:
  """Read-only slice of a data source."""

  def __init__(self, source, start, end):
    self._source = source
    self._start = start
    self._size = end - start

  def __len__(self):
    return self._size

  def __getitem__(self, idx):
    return self._source[idx % self._size + self._start]


def print_dataset_stats(source, args):
  """Print dataset statistics."""
  print("=" * 60)
  print("Dataset Statistics")
  print("=" * 60)
  print(f"  Scatter dir(s):   {args.scatter_dir}")
  print(f"  Mode:             {args.mode}")
  print(f"  Seq length:       {args.seq_length} (internal: {args.seq_length + 1})")
  print(f"  EOS token ID:     {args.eos_token_id}")
  print(f"  Total samples:    {len(source)}")
  if args.weights:
    print(f"  Blend weights:    {args.weights}")

  # Per-scatter stats
  for scatter_dir in args.scatter_dir:
    from pathlib import Path

    scatter_path = Path(scatter_dir)
    lazy_dirs = sorted(scatter_path.glob("*.lazy"), key=lambda p: int(p.stem))
    total_tokens = 0
    total_docs = 0
    for lazy_dir in lazy_dirs:
      ds = LazyIndexedDataset(str(lazy_dir), args.data_type)
      total_tokens += ds.total_tokens
      total_docs += ds.num_docs
      ds.close()
    print(f"\n  [{scatter_path.name}]")
    print(f"    Shards:         {len(lazy_dirs)}")
    print(f"    Total docs:     {total_docs:,}")
    print(f"    Total tokens:   {total_tokens:,}")
    if total_docs > 0:
      print(f"    Avg doc len:    {total_tokens / total_docs:.1f}")
  print("=" * 60)


def load_tokenizer(path):
  """Try to load a HuggingFace tokenizer."""
  try:
    from transformers import AutoTokenizer

    return AutoTokenizer.from_pretrained(path, trust_remote_code=True)
  except Exception as e:
    print(f"Warning: could not load tokenizer from {path}: {e}")
    return None


def dump_sample(index, sample, eos_token_id=2, tokenizer=None, decode=True):
  """Print a single sample."""
  tokens = sample["text"] if isinstance(sample, dict) else sample
  tokens = np.asarray(tokens)

  print(f"\n--- Sample {index} (length={len(tokens)}) ---")
  print(f"  Tokens[:30]: {tokens[:30].tolist()}")
  if len(tokens) > 30:
    print(f"  Tokens[-10:]: {tokens[-10:].tolist()}")

  # Token statistics
  unique, _ = np.unique(tokens, return_counts=True)
  eos_count = int(np.sum(tokens == eos_token_id))
  print(f"  Unique tokens: {len(unique)}, EOS count: {eos_count}")

  # Find EOS positions (document boundaries)
  eos_positions = np.where(tokens == eos_token_id)[0]
  if len(eos_positions) > 0:
    print(f"  EOS positions: {eos_positions.tolist()[:20]}{'...' if len(eos_positions) > 20 else ''}")

  # Decode if tokenizer available
  if tokenizer is not None and decode:
    try:
      text = tokenizer.decode(tokens.tolist(), skip_special_tokens=False)
      # Show first 200 chars
      preview = text[:200]
      if len(text) > 200:
        preview += "..."
      print(f"  Decoded: {repr(preview)}")
    except Exception as e:
      print(f"  Decode error: {e}")


def _trace_sample(source, global_idx):
  """Print routing trace for a sample through the pipeline."""
  from bisect import bisect_right as _bisect

  # Walk through the source chain
  src = source
  idx = global_idx

  # _SliceSource layer
  if hasattr(src, "_source") and hasattr(src, "_start"):
    mapped = idx % src._size + src._start
    print(f"    SliceSource: idx={idx} -> mapped={mapped} (start={src._start}, size={src._size})")
    src = src._source
    idx = mapped

  # LazyBlendedDataSource layer
  if hasattr(src, "_dataset_sample_index"):
    ds_idx = int(src._dataset_index[idx])
    sample_idx = int(src._dataset_sample_index[idx])
    inner_src = src._sources[ds_idx]
    local_idx = sample_idx % len(inner_src)
    print(f"    Blend: idx={idx} -> ds={ds_idx}, sample_idx={sample_idx}, local={local_idx} (src_len={len(inner_src)})")
    src = inner_src
    idx = local_idx

  # MultiShardLazyDataSource layer
  if hasattr(src, "_cnt_ends"):
    shard = _bisect(src._cnt_ends, idx)
    inner = idx - (int(src._cnt_ends[shard - 1]) if shard > 0 else 0)
    print(f"    MultiShard: local={idx} -> shard={shard}, inner={inner}")


def _debug_binary(scatter_dir, seq_length, eos_token_id, data_type, mode):
  """Print raw binary diagnostics for each shard in a scatter directory."""
  from pathlib import Path

  scatter_path = Path(scatter_dir)
  lazy_dirs = sorted(scatter_path.glob("*.lazy"), key=lambda p: int(p.stem))
  if not lazy_dirs:
    # Check for hash subdirectory
    sub_dirs = [d for d in scatter_path.iterdir() if d.is_dir() and not d.name.endswith(".lazy")]
    if len(sub_dirs) == 1:
      lazy_dirs = sorted(sub_dirs[0].glob("*.lazy"), key=lambda p: int(p.stem))
  if not lazy_dirs:
    print(f"  ERROR: No .lazy directories found in {scatter_dir}")
    return

  effective_seq = seq_length + 1
  print(f"\n{'='*60}")
  print(f"Binary Diagnostics for {scatter_dir}")
  print(f"  mode={mode}, seq_length={seq_length} (internal={effective_seq}), eos={eos_token_id}")
  print(f"  Found {len(lazy_dirs)} .lazy shards")
  print(f"{'='*60}")

  for shard_idx, lazy_dir in enumerate(lazy_dirs[:3]):  # First 3 shards
    print(f"\n--- Shard {shard_idx}: {lazy_dir.name} ---")
    bin_path = str(lazy_dir / data_type)
    lens_path = str(lazy_dir / f"{data_type}.lens.npy")

    # 1. Raw binary tokens
    try:
      fd = os.open(bin_path, os.O_RDONLY)
      raw_bytes = os.pread(fd, 120, 0)  # 30 int32 tokens
      os.close(fd)
      raw_tokens = np.frombuffer(raw_bytes, dtype=np.int32)
      print(f"  Raw binary first 30 tokens: {raw_tokens.tolist()}")
    except Exception as e:
      print(f"  ERROR reading binary: {e}")
      continue

    # 2. Document lengths
    try:
      lens = np.load(lens_path)
      ends = np.cumsum(lens)
      total_tokens = int(ends[-1])
      num_docs = len(lens)
      print(f"  num_docs={num_docs}, total_tokens={total_tokens}")
      print(f"  First 10 doc lengths: {lens[:10].tolist()}")
      print(f"  First 10 cumulative ends: {ends[:10].tolist()}")
    except Exception as e:
      print(f"  ERROR reading lens: {e}")
      continue

    # 3. LazyIndexedDataset read_range
    try:
      ds = LazyIndexedDataset(str(lazy_dir), data_type)
      range_tokens = ds.read_range(0, min(30, total_tokens))
      print(f"  read_range(0, 30): {range_tokens.tolist()}")
      ds.close()
    except Exception as e:
      print(f"  ERROR with read_range: {e}")

    # 4. Sliding window sample 0
    if mode == "sliding_window":
      try:
        ds = LazyIndexedDataset(str(lazy_dir), data_type)
        from maxtext.input_pipeline._lazy_datasource import LazySlidingWindowDataSource

        sw = LazySlidingWindowDataSource(ds, effective_seq, eos_token_id)
        if len(sw) > 0:
          sample0 = sw[0]
          tokens = sample0["text"] if isinstance(sample0, dict) else sample0
          tokens = np.asarray(tokens)
          print(f"  SlidingWindow[0] (len={len(tokens)}): first 30 = {tokens[:30].tolist()}")
          # Show where first EOS injection happens
          eos_pos = np.where(tokens == eos_token_id)[0]
          if len(eos_pos) > 0:
            first_eos = int(eos_pos[0])
            print(f"  First EOS at position {first_eos} (doc 0 length={int(lens[0])})")
        else:
          print(f"  SlidingWindow has 0 samples (total_tokens={total_tokens}, seq={effective_seq})")
        ds.close()
      except Exception as e:
        print(f"  ERROR with SlidingWindow: {e}")

  print(f"\n{'='*60}\n")


def _print_blend_debug(source, consumed_samples, batch_per_step, num_steps, step_indices=None):
  """Print blend-epoch diagnostics for the given source and access range."""
  # Unwrap _SliceSource if present
  src = source
  slice_start = 0
  if hasattr(src, "_source") and hasattr(src, "_start"):
    slice_start = src._start
    src = src._source

  if not hasattr(src, "_dataset_index"):
    print("  [debug-blend] Source is not a LazyBlendedDataSource, skipping.")
    return

  blend_size = src._size

  print(f"\n  {'='*60}")
  print("  Blend-Epoch Diagnostics")
  print(f"  {'='*60}")
  print(f"  blend _size (samples per blend pass):  {blend_size:,}")
  print(f"  blend __len__:                          {len(src):,}")

  # Per-dataset blend allocation and sub-source details
  ds_index = src._dataset_index
  ds_sample_index = src._dataset_sample_index
  for i, sub in enumerate(src._sources):
    sub_total = getattr(sub, "_total_samples", len(sub))
    sub_shuffle = getattr(sub, "_loader_online_shuffle", False)
    sub_mode = getattr(sub, "_mode", "unknown")
    sub_scatter = getattr(sub, "_scatter_dir", "?")
    # How many blend slots point to this dataset
    mask = ds_index == i
    blend_count = int(mask.sum())
    # Max dataset_sample_index for this dataset in one blend pass
    max_sample_idx = int(ds_sample_index[mask].max()) if blend_count > 0 else 0
    crosses_sub_epoch = max_sample_idx >= sub_total
    print(f"  sub-source[{i}]: {os.path.basename(sub_scatter)}")
    print(f"    mode={sub_mode}, total_samples={sub_total:,}, " f"loader_online_shuffle={sub_shuffle}")
    print(
        f"    blend_slots={blend_count:,} (ratio={blend_count/blend_size:.4f}), "
        f"max_sample_idx={max_sample_idx:,}, crosses_sub_epoch={crosses_sub_epoch}"
    )

  # Compute the actual indices that will be accessed
  steps = step_indices if step_indices is not None else list(range(num_steps))
  if not steps:
    print(f"  {'='*60}\n")
    return

  first_step, last_step = steps[0], steps[-1]
  first_idx = consumed_samples + first_step * batch_per_step
  last_idx = consumed_samples + last_step * batch_per_step + (batch_per_step - 1)

  # Simulate the actual index seen by blend's __getitem__:
  # 1. _dump_split_source wraps: global_idx % len(source)
  # 2. _SliceSource (if split) further maps: idx % slice_size + slice_start
  # Without split, len(source) = _size * num_epochs (inflated), so blend
  # can see idx >= _size → blend_epoch > 0.
  # With split, len(source) = slice_size (un-inflated), and the mapped
  # index is always < _size → blend_epoch = 0.
  outer_len = len(source)
  is_split = hasattr(source, "_start")
  if is_split:
    slice_size = source._size
    first_mapped = first_idx % slice_size + slice_start
    last_mapped = last_idx % slice_size + slice_start
  else:
    first_mapped = first_idx % outer_len
    last_mapped = last_idx % outer_len

  first_blend_epoch = first_mapped // blend_size
  last_blend_epoch = last_mapped // blend_size

  cross_epoch_threshold_step = (blend_size - consumed_samples) / batch_per_step if batch_per_step > 0 else float("inf")

  print(f"\n  Access range (split={is_split}, outer_len={outer_len:,}):")
  print(f"    consumed_samples={consumed_samples:,}, batch_per_step={batch_per_step}")
  print(
      f"    first global_idx={first_idx:,} -> blend_idx={first_mapped:,}"
      f" (step {first_step}), blend_epoch={first_blend_epoch}"
  )
  print(
      f"    last  global_idx={last_idx:,} -> blend_idx={last_mapped:,} (step {last_step}), blend_epoch={last_blend_epoch}"
  )
  if is_split:
    print(
        f"    ** split active: blend_idx always in [{slice_start}, {slice_start + slice_size}), blend_epoch always 0 **"
    )
  else:
    print(f"    blend_epoch crosses >0 at step ~{cross_epoch_threshold_step:,.1f}")

  if last_blend_epoch == 0:
    print("\n  ** All accessed indices are in blend_epoch=0. **")
    print("  ** The cross-blend-epoch patch has NO effect at these steps. **")
  else:
    print("\n  ** blend_epoch > 0 reached! The cross-blend-epoch patch DOES matter. **")
    has_shuffle = any(getattr(s, "_loader_online_shuffle", False) for s in src._sources)
    if not has_shuffle:
      print("  ** BUT loader_online_shuffle=False on all sub-sources, **")
      print("  ** so the offset gets mod-ed away — data is identical anyway. **")
    else:
      print("  ** AND loader_online_shuffle=True on some sub-sources, **")
      print("  ** so epoch shuffle ordering WILL differ between old/new code. **")

  print(f"  {'='*60}\n")


def _build_source_for_group(args, process_index):
  """Build a full-pipeline source (blend/shuffle/split) for a specific scatter group.

  Same as build_source() but overrides process_index for the given group.
  """
  saved_process_index = args.process_index
  args.process_index = process_index
  try:
    source = build_source(args)
  finally:
    args.process_index = saved_process_index
  return source


def _dump_split_source(
    source,
    split_name,
    base_dir,
    num_steps,
    batch_per_step,
    digest=False,
    group_id=0,
    consumed_samples=0,
    step_indices=None,
):
  """Dump samples from a single source into base_dir/<group_id>/step_*.npy structure.

  Args:
    step_indices: If provided, dump these specific step indices instead of
      range(num_steps). Each step index determines which samples to read via
      global_idx = consumed_samples + step * batch_per_step + j.
  """
  group_samples = len(source)
  steps_to_dump = step_indices if step_indices is not None else list(range(num_steps))
  print(f"    [{split_name}] samples={group_samples}, consumed_samples={consumed_samples}, steps={len(steps_to_dump)}")

  digest_file = None
  if digest:
    digest_path = os.path.join(base_dir, f"digest_rank{group_id}.jsonl")
    digest_file = open(digest_path, "w", encoding="utf-8")  # pylint: disable=consider-using-with

  try:
    sample_count = 0
    for step in steps_to_dump:
      step_tokens = []
      for j in range(batch_per_step):
        global_idx = consumed_samples + step * batch_per_step + j
        if global_idx >= group_samples:
          global_idx = global_idx % group_samples
        sample = source[global_idx]
        tokens = sample["text"] if isinstance(sample, dict) else np.asarray(sample)
        tokens = np.asarray(tokens)[:-1]  # inputs = text[:-1]
        step_tokens.append(tokens)
        sample_count += 1

      batch_arr = np.stack(step_tokens, axis=0).astype(np.int32)
      if digest_file is not None:
        record = {
            "step": step,
            "rank": group_id,
            "shape": list(batch_arr.shape),
            "token_sum": int(batch_arr.sum()),
            "sha256": hashlib.sha256(batch_arr.tobytes()).hexdigest(),
        }
        digest_file.write(json.dumps(record) + "\n")
      else:
        np.save(os.path.join(base_dir, f"step_{step:06d}.npy"), batch_arr)

      if sample_count <= 3 * batch_per_step or step == steps_to_dump[-1]:
        print(f"      Step {step}: batch shape={batch_arr.shape}, first_token={int(step_tokens[0][0])}")
  finally:
    if digest_file is not None:
      digest_file.close()

  return sample_count


def _dump_groups(args):
  """Dump samples from every scatter group, mirroring antllm's check_outputs.py.

  antllm iterates `for rank in range(abs(loader_scatter))` where each rank
  represents one scatter group with `world_size=abs(scatter)`. This function
  replicates that: for each group, build a full-pipeline source (including
  multi-dataset blending, shuffle, and split) and consume batch_per_step
  samples sequentially per step.

  Output structure (single split):
    <output-dir>/<group_id>/step_<N>.npy
  Output structure (multiple splits, e.g. --split-parts train,valid):
    <output-dir>/train/<group_id>/step_<N>.npy
    <output-dir>/valid/<group_id>/step_<N>.npy
  """
  if not args.output_dir:
    raise ValueError("--dump-groups requires --output-dir")

  scatter = abs(args.loader_scatter)
  if scatter <= 1:
    raise ValueError("--dump-groups requires |loader_scatter| > 1")

  num_steps = args.num_steps
  batch_per_step = args.batch_per_step if args.batch_per_step else args.num_samples
  digest = getattr(args, "digest", False)
  consumed_samples = getattr(args, "consumed_steps", 0) * batch_per_step

  # Build step indices: sequential or random sampling
  step_indices = None
  if args.random_steps:
    step_start, step_end = args.step_range if args.step_range else [0, num_steps]
    rng = np.random.RandomState(args.seed)
    step_indices = sorted(
        int(step) for step in rng.choice(np.arange(step_start, step_end), size=args.random_steps, replace=False)
    )

  print(f"{'='*70}")
  print("Dumping ALL scatter groups (full pipeline: blend/shuffle/split)")
  print(f"{'='*70}")
  print(f"  loader_scatter={args.loader_scatter}, groups={scatter}")
  print(f"  scatter_dirs={args.scatter_dir}")
  print(f"  split_parts={args.split_parts}")
  print(f"  batch_per_step={batch_per_step}, num_steps={num_steps}")
  print(f"  consumed_steps={args.consumed_steps}, consumed_samples={consumed_samples}")
  if step_indices is not None:
    print(f"  random_steps={len(step_indices)}, step_range=[{step_start}, {step_end}), seed={args.seed}")
  print(f"  digest={digest}")
  print(f"  output_dir={args.output_dir}")
  print()

  for group_id in range(scatter):
    print(f"  --- Group {group_id} (process_index={group_id}) ---")
    sources_dict = _build_source_for_group(args, process_index=group_id)
    multi_split = len(sources_dict) > 1

    if getattr(args, "debug_blend", False):
      for split_name, source in sources_dict.items():
        print(f"  [{split_name}] blend-epoch debug (group {group_id}):")
        _print_blend_debug(source, consumed_samples, batch_per_step, num_steps, step_indices)

    for split_name, source in sources_dict.items():
      if digest:
        group_dir = args.output_dir
        if multi_split:
          group_dir = os.path.join(args.output_dir, split_name)
      elif multi_split:
        group_dir = os.path.join(args.output_dir, split_name, str(group_id))
      else:
        group_dir = os.path.join(args.output_dir, str(group_id))
      os.makedirs(group_dir, exist_ok=True)

      sample_count = _dump_split_source(
          source,
          split_name,
          group_dir,
          num_steps,
          batch_per_step,
          digest=digest,
          group_id=group_id,
          consumed_samples=consumed_samples,
          step_indices=step_indices,
      )

      actual_steps = len(step_indices) if step_indices else num_steps
      if actual_steps > 4:
        print(f"      ... ({actual_steps - 4} steps omitted)")
      print(f"      Total: {sample_count} samples saved to {group_dir}/")
    print()

  print(f"{'='*70}")
  if digest:
    print(f"Done. Output: {args.output_dir}/digest_rank*.jsonl")
  elif multi_split:
    print(f"Done. Output: {args.output_dir}/<split>/<group_id>/step_*.npy")
  else:
    print(f"Done. Output: {args.output_dir}/<group_id>/step_*.npy")
  print(f"{'='*70}")


def main():
  args = get_args()
  tic = time.time()

  if args.dump_groups:
    _dump_groups(args)
    return

  if args.debug_binary:
    for scatter_dir in args.scatter_dir:
      _debug_binary(scatter_dir, args.seq_length, args.eos_token_id, args.data_type, args.mode)

  print(f"Building data source (mode={args.mode})...")
  if args.raw:
    # Build only the MultiShardLazyDataSource (no blend/shuffle/split)
    effective_seq = args.seq_length + 1
    cls_token_id = args.cls_token_id if args.cls_token_id >= 0 else None
    source = MultiShardLazyDataSource(
        scatter_dir=args.scatter_dir[0],
        mode=args.mode,
        seq_length=effective_seq,
        eos_token_id=args.eos_token_id,
        data_type=args.data_type,
        cls_token_id=cls_token_id,
        add_cls=args.add_cls,
        drop_last=not args.no_drop_last,
        loader_online_shuffle=args.loader_online_shuffle,
        loader_seed=args.loader_seed,
        index_mapping_path=args.index_mapping_path,
        bin_index_base_path=args.bin_index_path,
        bfd_pack_sort_by_lens=args.bfd_pack_sort_by_lens,
        loader_scatter=args.loader_scatter,
        process_index=args.process_index,
    )
    print(f"  [RAW] shards={len(source._loaders)}, samples={len(source)}")
    print(f"  loader_online_shuffle={args.loader_online_shuffle}, loader_seed={args.loader_seed}")
    print(f"  loader_scatter={args.loader_scatter}, process_index={args.process_index}")
    sources_dict = {"train": source}
  else:
    sources_dict = build_source(args)
  build_time = time.time() - tic
  for name, src in sources_dict.items():
    print(f"Built [{name}] in {build_time:.2f}s, total samples: {len(src)}")

  if getattr(args, "debug_blend", False):
    for name, src in sources_dict.items():
      print(f"  [{name}] blend-epoch debug:")
      _print_blend_debug(src, args.start_index, 1, args.num_samples)

  if args.show_stats:
    print_dataset_stats(list(sources_dict.values())[0], args)

  # Load tokenizer if requested
  tokenizer = None
  if args.tokenizer_path and not args.no_decode:
    tokenizer = load_tokenizer(args.tokenizer_path)

  # Dump samples for each split part
  for split_name, source in sources_dict.items():
    multi_split = len(sources_dict) > 1
    if multi_split:
      split_output_dir = os.path.join(args.output_dir, split_name) if args.output_dir else None
    else:
      split_output_dir = args.output_dir

    if split_output_dir:
      os.makedirs(split_output_dir, exist_ok=True)

    end_index = min(args.start_index + args.num_samples, len(source))
    actual_count = end_index - args.start_index
    if actual_count <= 0:
      print(f"No samples to dump for [{split_name}] (start={args.start_index}, total={len(source)})")
      continue

    print(f"\nDumping [{split_name}] samples [{args.start_index}, {end_index})...")
    for i in range(args.start_index, end_index):
      if args.trace and not args.raw:
        _trace_sample(source, i)
      sample = source[i]
      # Source outputs seq_length+1 tokens (antllm convention).
      # Take inputs = text[:-1] to match training split (MegatronSplitInputsTargets).
      tokens = sample["text"] if isinstance(sample, dict) else sample
      tokens = np.asarray(tokens)[:-1]
      sample = {"text": tokens}
      dump_sample(i, sample, eos_token_id=args.eos_token_id, tokenizer=tokenizer, decode=not args.no_decode)

      if split_output_dir:
        np.save(os.path.join(split_output_dir, f"sample_{i:06d}.npy"), tokens)

    if split_output_dir:
      print(f"\nSaved {actual_count} [{split_name}] samples to {split_output_dir}/")

  print(f"\nTotal time: {time.time() - tic:.2f}s")


if __name__ == "__main__":
  main()
